//
//  CommonMacro.h
//  Accountant
//
//  Created by aaa on 2017/3/1.
//  Copyright © 2017年 tianming. All rights reserved.
//

#ifndef CommonMacro_h
#define CommonMacro_h


#define isObjectNotNil(a) (a != nil)

#define kAppointUserID      @"10214哈哈哈"

#define kCurrentCatogoryInfo    @"currentCatogoryInfo"
#define kCurrentTestSecondCatogoryInfo    @"currentTestSecondCatogoryInfo"

#define kSubjectId    @"subjectId"
#define kPaperTypeId    @"paperTypeId"
#define kUserId    @"userId"

#define kTop    @"Top"
#define kOneId  @"OneId"
#define kOneName    @"OneName"
#define kUid    @"accountId"
#define kParent @"parent"
#define kUrlName    @"urlName"
#define kCid        @"Cid"
#define kState      @"State"
#define kTwoId      @"TwoId"
#define kTwoName    @"TwoName"
#define kTeacherId  @"TeaId"
#define kSort       @"sort"
#define kPageNo       @"pageNo"
#define kPageSize   @"pageSize"
#define kCourseId   @"CourseId"
#define kIsMf       @"IsMf"
#define kImg        @"Img"
#define kContent    @"Content"
#define kAnswerId   @"AnswerId"
#define kTypeName   @"TypeName"
#define kNoCode     @"NoCode"
#define kTypeId     @"typeId"
#define ksjid       @"sjid"
#define kscid       @"scid"

#define ktgid       @"tgid"
#define kstId       @"stId"
#define kLname      @"Lname"
#define klid       @"lid"
#define kNName       @"NName"
#define ktaid       @"taid"
#define ktbid       @"tbid"
#define kSTNo       @"STNo"
#define kzong       @"zong"
#define kSJID       @"SJID"



#define kCourseName         @"courseName"
#define kCourseURL          @"courseURLString"
#define kCourseCover        @"coverImg"
#define kCourseTeacherName  @"teacherName"
#define kteacherId          @"tacherId"
#define kCourseID           @"courseID"
#define kCoursePath         @"coursePath"
#define kCourseChapterInfos @"courseChapterInfos"
#define kCourseIsCollect    @"courseIsCollect"
#define kCourseCanDownLoad  @"courseCanDownload"
#define kCanWatch           @"courseCanWatch"
#define kLearnProgress      @"courseLearnProgress"
#define kPrice              @"price"
#define kOldPrice           @"oldPrice"
#define kRealityPrice       @"realityPrice"
#define kIsDownload         @"isDownload"
#define kIsRecommend        @"isRecommend"
#define kisSubscribe        @"isSubscribe"

#define kLivingTime         @"livingTime"
#define kLivinglastTime     @"lastTime"
#define kLivingState        @"livingState"
#define kTeacherDetail      @"teacherDetail"
#define kLivingDetail       @"livingDetail"
#define kTeacherPortraitUrl @"teacherPortraitUrl"
#define kChatRoomID         @"chatRoomId"
#define kAssistantID        @"assistantId"
#define kPlayBackUrl        @"playBackUrl"
#define kHaveJurisdiction   @"haveJurisdiction"
#define kIsLivingCourseFree @"isLivingCOurseFree"
#define kIsBack             @"isBack"
#define kRtmpUrl            @"rtmpUrl"
#define kBeginLivingTime    @"beginLivingTime"
#define kEndLivingTime      @"endLivingTime"


#define kLivingCourseArr    @"livingCourseArr"
#define kSectionArray       @"sectionArray"

#define kCourseSecondName         @"courseSecondName"
#define kCourseSecondCover        @"courseSecondCover"
#define kCourseSecondID           @"courseSecondID"
#define kCourseCategorySecondCourseInfos      @"courseCategorySecondCourseInfos"

#define kIsFold                 @"isFold"

#define kChapterName        @"chapterName"
#define kChapterURL         @"chapterURLString"
#define kChapterId          @"chapterId"
#define kChapterPath        @"chapterPath"
#define kChapterSort        @"chapterSort"
#define kIsSingleChapter    @"isSingleChapter"
#define kChapterCourseId    @"chapterCourseId"
#define kChapterVideoInfos  @"chapterVideoInfos"

#define kVideoName          @"videoName"
#define kVideoURL           @"videoURL"
#define kVideoId            @"videoId"
#define kVideoSort          @"videoSort"
#define kVideoPath          @"videoPath"
#define kVideoPlayTime      @"videoPlayTime"
#define kVideoChapterId     @"videoChapterId"
#define kVideoIsChapterVideo    @"videoIsChapterVideo"
#define kCanDownload        @"videoCanDownload"

#define kQuestionContent                @"questionContent"
#define kQuestionQuizzerHeaderImageUrl  @"questionQuizzerHeaderImageUrl"
#define kQuestionQuizzerUserName        @"questionQuizzerName"
#define kQuestionQuizzerUserNickName    @"questionQuizzerNickName"
#define kQuestionQuizzerId              @"questionQuizzerId"
#define kQuestionId                     @"questionId"
#define kQuestionTitle                  @"questionTitle"
#define kQuestionClassId                @"questionClassId"
#define kQuestionTime                   @"questionTime"
#define kQuestionSeePeopleCount         @"questionSeePeopleCount"
#define kQuestionReplyCount             @"questionReplyCount"
#define kQuestionImgStr                 @"questionImagesStr"


#define kUserId                         @"userId"
#define kUserName                       @"userName"
#define kUserNickName                   @"userNickName"
#define kUserLevel                      @"userLevel"
#define kUserHeaderImageUrl             @"userHeaderImageUrl"
#define kUserTelephone                  @"userTelephone"
#define kUserLevel                      @"userLevel"
#define kUserLevelDetail                @"levelDetail"
#define kUserSex                        @"sex"
#define kOpenId                        @"openId"

#define kMemberLevel                    @"memberLevel"
#define kMemberLevelId                  @"memberID"
#define kMemberLevelDetailIconUrl       @"memberDeUrl"


#define kCourseCategoryName             @"courseCategoryName"
#define kCourseCategoryId               @"courseCategoryId"
#define kCourseCategoryCoverUrl         @"courseCategoryCoverUrl"
#define kCourseCategoryCourseInfos      @"courseCategoryCourseInfos"
#define kCourseIsStartFromLoaction      @"courseIsStartFromLocation"

#define kReplyContent                   @"replyContent"
#define kReplyTime                      @"replyTime"
#define kReplyId                      @"replyId"
#define kReplierHeaderImage             @"replierHeaderImageUrl"
#define kReplierUserName                @"replierUserName"
#define kAskedArray                     @"askedArray"

#define kTestCategoryName               @"testCategoryName"
#define kTestCategoryImageName          @"testCategoryImageName"
#define kTestCategoryId                 @"testCategoryId"
#define kTestSimulateTestId             @"testSimulateTestId"
#define kTestSimulateTestAnswers        @"testSimulateTestAnswers"
#define kTestChapterName                @"testChapterName"
#define kTestChapterId                  @"testChapterId"
#define kTestChapterQuestionCount       @"testChapterQuestionCount"
#define kTestChapterSectionArray        @"testChapterSectionArray"
#define kTestSectionQuestionCount        @"testSectionQuestionCount"
#define kTestSectionId                  @"testSectionId"
#define kTestSectionName                @"testSectionName"
#define kTestSectionQuestionArray       @"testSectionQuestionArray"
#define kTestSimulateName               @"testSimulateName"
#define kTestSimulateId                 @"testSimulateId"
#define kTestQuestionResult             @"testQuestionResult"
#define kTestSimulateQuestionCount      @"testSimulateQuestionCount"
#define kTestQuestionId                 @"testQuestionId"
#define kTestQuestionIndex              @"testQuestionIndex"
#define kTestQuestionIsAnswered         @"testQuestionIsAnswered"
#define kTestQuestionIsShowAnswer       @"testQuestionIsShowAnswer"
#define kTestQuestionAnswers            @"testQuestionAnswers"
#define kTestQuestionSelectedAnswers    @"testQuestionSelectAnswers"
#define kTestQuestionSelectedAnswersId  @"testQuestionSelectAnswersId"
#define kTestQuestionComplain           @"testQuestionComplain"
#define kTestQuestionContent            @"testQuestionContent"
#define kTestQuestionType               @"testQuestionType"
#define kTestQuestionTypeId             @"testQuestionTypeId"
#define kTestQuestionCorrectAnswersId   @"testQuestionCorrectAnswersId"
#define kTestQuestionIsCollected        @"testQuestionIsCollected"
#define kTestQuestionIsAnswerCorrect    @"testQuestionIsAnswerCorrect"
#define kTestQuestionNumber             @"testQuestionNumber"
#define kTestAnswerContent              @"testAnswerContent"
#define kTestAnserId                    @"testAnswerId"
#define kTestAddHistoryType             @"testHistoryType"
#define kTestAddDetailHistoryLogId      @"testAddQuestionLogId"
#define kQuestionCaseInfo               @"testSimulateQuestionCaseInfo"
#define kLastLogId                      @"lastLogId"

#define kTestIsEasyWrong                @"isEasyWrong"
#define kLogName                        @"logName"
#define kLID                            @"directionId"
#define kKID                            @"subjectId"
#define kTestMyanswer                   @"myAnswer"
#define kTestIsResponse                 @"isResponse"


#define kRightquistionArr               @"rightquestionarr"
#define kWrongquistionArr               @"wrongquestionarr"
#define kDataArray                      @"dataArray"
#define kSinglequistionArr              @"singlequestionarr"
#define kMultiplequistionArr            @"multiplequestionarr"
#define kJudgequistionArr               @"judgequestionarr"
#define kMaterailQuestionArray          @"materailQuestionArr"
#define kJiandaQuestionArray            @"jiandaQuestionArray"
#define kAnalisisQuestionArray          @"analisisQuestionArray"
#define kZongheQuestionArray            @"zongheQuestionArray"

#define kDownloadTaskId                 @"downloadTaskId"
#define kDownloadState                  @"downloadState"

#define kHistoryTime                    @"historyTime"
#define kHistoryInfos                   @"historyInfos"

#define kNoteVideoNoteId                @"videoNoteId"
#define kNoteVideoNoteContent           @"videoNoteContent"

#define kAppUpdateInfoUrl               @"appUpdateInfoUrl"
#define kAppUpdateInfoVersion           @"appUpdateInfoVersion"
#define kAppUpdateInfoContent           @"appUpdateInfoContent"
#define kAppUpdateInfoIsForce           @"appUpdateInfoIsForce"

#define kDBErrorType_Mywrong            @"myWrong"
#define kDBErrorType_Easywrong            @"easyWrong"
#define kDBErrorType_Collect            @"colection"

#define kOrderId                        @"orderID"
#define kOrderTime                      @"orderTime"
#define kOrderDetail                    @"orderDetail"
#define kRemark                         @"remark"
#define kDeadLineTime                   @"deadLineTime"
#define kOrderStatus                    @"orderStatus"

#define kRecommendPackageId             @"recommendPackageId"
#define kRecommendPackageCover          @"recommendPackageCover"

#define kPackageTypeId                  @"packageTypeId"
#define kPackageTypename                @"packageTypename"
#define kPackageId                      @"packageId"
#define kPackageName                    @"packageName"
#define kPackageCover                   @"packageCover"
#define kPackagePrice                   @"packagePrice"


#endif /* CommonMacro_h */

